name: Build

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  schedule:
    - cron: "0 0 * * 1"
  pull_request:

jobs:
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          # toolchain: "nightly"

        # - name: rust
        #   run: |
        #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly

        # - name: config
        #   run: |
        #     echo "${GITHUB_WORKSPACE}/git-cinnabar" >> $GITHUB_ENV
      - name: Build
        env:
          MOZCONFIG: ${{ env.HOME }}/mozconfigs/optimized
        run: |
          python3 -m pip install --user mercurial
          hg version

          cargo install --locked git-cinnabar

          echo "" >> ~/.bashrc
          echo export PATH='$PATH:~/git-cinnabar' >> ~/.bashrc
          echo 'export PATH="'"$(python3 -m site --user-base)"'/bin:$PATH"' >> ~/.bashrc

          # echo \n export PATH='"$PATH:'$(pwd)/git-cinnabar\" >> ~/.bashrc
          source ~/.bashrc

          echo $PATH
          echo $MOZCONFIG
          # export PATH="$PATH:$(pwd)/git-cinnabar"
          # echo $PATH

          # python3 --version
          # # python3 -m pip install --user mercurial
          # # hg version

          mkdir ~/git-cinnabar
          cd ~/git-cinnabar
          wget https://raw.githubusercontent.com/glandium/git-cinnabar/master/download.py
          python3 ./download.py
          git cinnabar setup
          cd ..

          cp -r ./mozconfigs $HOME/mozconfigs
          # export MOZCONFIG=$HOME/mozconfigs/optimized

          wget https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py
          # To use Git as your VCS
          python3 bootstrap.py

          # git clone https://github.com/mozilla/gecko-dev.git mozilla-unified --depth=1

          cd mozilla-unified
          # hg up -C central
          sudo ./mach bootstrap
          sudo ./mach build
          sudo apt install tree -y
          tree ./ > tree.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spidermonkey-x86_64-unknown-linux-gnu
          path: ./mozilla-unified/.mozbuild,./mozilla-unified/tree.txt
  build:
    needs: [
        "build-x86_64-unknown-linux-gnu",
        # "build-windows",
        # "build-macos-x86_64",
        # "build-macos-aarch64",
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: spidermonkey
          pattern: spidermonkey-*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "spidermonkey/*.tar.gz"
